### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by Fawke** [sanzacha/react-movie-app-assignment-4#1]
1. Use template literals wherever possible.
```javascript
 searchMovies(searchTerm) {
        fetch('https://api.themoviedb.org/3/search/movie?api_key=f58323742f0d3b835da1b436ef1eada3&query='+searchTerm)
        .then(res => res.json())
        .then(
        (response) => {
            this.setState({
                isLoaded: true,
                movies: response.results
            });
        },
        (error) => {
            this.setState({
                isLoaded: true,
                error
            });
        }) 
    }
```
you could have used template literal to give your url to fetch call

2. Incomplete funtionality. Unable to create user collections.
3. Alignments of the cards is not proper.
4. Do prop type checking.
5. Redux store missing.

**Comment by Fawke** [comment]
Hi @sanzacha , did you refactor your code? If yes, let me know, I'll mark it as completed.

**Comment by sanzacha** [comment]
Code refactored.

**Comment by Fawke** [comment]
This assignment is being marked complete!
